// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $HeroEngine from "./islands/HeroEngine.tsx";
import * as $InstallCmd from "./islands/InstallCmd.tsx";
import * as $InteractiveConsole from "./islands/InteractiveConsole.tsx";
import * as $LiveTerminal from "./islands/LiveTerminal.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/HeroEngine.tsx": $HeroEngine,
    "./islands/InstallCmd.tsx": $InstallCmd,
    "./islands/InteractiveConsole.tsx": $InteractiveConsole,
    "./islands/LiveTerminal.tsx": $LiveTerminal,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
